template_data_file_name_list:
  - 20201110_132610_simple_network_L_1_exported_output.hdf5
  - 20201110_132610_simple_network_L_2_exported_output.hdf5
  - 20201110_132610_simple_network_L_3_exported_output.hdf5
  - 20201110_132610_simple_network_L_4_exported_output.hdf5
  - 20201110_132610_simple_network_L_5_exported_output.hdf5
replay_data_file_name_list:
  - 20201110_132936_simple_network_replay_L_1_exported_output.hdf5
  - 20201110_132936_simple_network_replay_L_2_exported_output.hdf5
  - 20201110_132940_simple_network_replay_L_3_exported_output.hdf5
  - 20201110_132939_simple_network_replay_L_4_exported_output.hdf5
  - 20201110_132939_simple_network_replay_L_5_exported_output.hdf5
pop_order:
  - FF
  - E
  - I
color_dict:
  FF: darkgrey
  E: r
  I: b
filter_order:
  - Theta
  - Gamma
filter_color_dict:
  Theta: g
  Gamma: purple
filter_xlim_dict:
  Theta:
    - 500.
    - 2000
  Gamma:
    - 500.
    - 1000.