data_file_name_list:
  - 20210113_121558_simple_network_K_1_heldout_exported_output.hdf5
  - 20210113_121558_simple_network_K_2_heldout_exported_output.hdf5
  - 20210113_121556_simple_network_K_3_heldout_exported_output.hdf5
  - 20210113_121848_simple_network_K_4_heldout_exported_output.hdf5
  - 20210113_121850_simple_network_K_5_heldout_exported_output.hdf5
pop_order:
  - FF
  - E
  - I
color_dict:
  FF: darkgrey
  E: r
  I: b
filter_order:
  - Theta
  - Gamma
filter_color_dict:
  Theta: g
  Gamma: purple
filter_xlim_dict:
  Theta:
    - 500.
    - 2000
  Gamma:
    - 500.
    - 1000.