bounds:
  E_FF_mean_weight: !!python/tuple
    - 0.1
    - 5.
  E_E_mean_weight: !!python/tuple
    - 0.1
    - 5.
  E_I_mean_weight: !!python/tuple
    - 0.1
    - 5.
  I_FF_mean_weight: !!python/tuple
    - 0.1
    - 5.
  I_E_mean_weight: !!python/tuple
    - 0.1
    - 5.
  I_I_mean_weight: !!python/tuple
    - 0.1
    - 5.
  E_FF_weight_norm_sigma: !!python/tuple
    - 0.1
    - 1.
  E_E_weight_norm_sigma: !!python/tuple
    - 0.1
    - 1.
  E_I_weight_norm_sigma: !!python/tuple
    - 0.1
    - 1.
  I_FF_weight_norm_sigma: !!python/tuple
    - 0.1
    - 1.
  I_E_weight_norm_sigma: !!python/tuple
    - 0.1
    - 1.
  I_I_weight_norm_sigma: !!python/tuple
    - 0.1
    - 1.
  E_E_tau_offset: !!python/tuple
    - 2.
    - 20.
  E_I_tau_offset: !!python/tuple
    - 2.
    - 30.
  I_E_tau_offset: !!python/tuple
    - 2.
    - 20.
  I_I_tau_offset: !!python/tuple
    - 2.
    - 30.
  E_E_syn_proportion: !!python/tuple
    - 0.01
    - 0.99
  E_E_FF_syn_proportion: !!python/tuple
    - 0.01
    - 0.99
  I_E_syn_proportion: !!python/tuple
    - 0.01
    - 0.99
  I_E_FF_syn_proportion: !!python/tuple
    - 0.01
    - 0.99
  E_norm_syn_count: !!python/tuple
    - 0.1
    - 1.
  I_norm_syn_count: !!python/tuple
    - 0.1
    - 1.
  E_peak_delta_weight: !!python/tuple
    - 1.
    - 5.0
rel_bounds:
feature_names:
- E_mean_peak_rate_run
- E_mean_min_rate_run
- I_mean_active_rate_run
- FF_frac_active_run
- E_frac_active_run
- I_frac_active_run
- FF_theta_envelope_ratio_run
- E_theta_envelope_ratio_run
- I_theta_envelope_ratio_run
- FF_gamma_envelope_ratio_run
- E_gamma_envelope_ratio_run
- I_gamma_envelope_ratio_run
- FF_ripple_envelope_ratio_run
- E_ripple_envelope_ratio_run
- I_ripple_envelope_ratio_run
- E_centroid_theta_freq_run
- I_centroid_theta_freq_run
- E_centroid_gamma_freq_run
- I_centroid_gamma_freq_run
- E_theta_tuning_index_run
- I_theta_tuning_index_run
- E_gamma_tuning_index_run
- I_gamma_tuning_index_run
- FF_frac_active_replay
- E_frac_active_replay
- E_frac_active_replay_residuals
- I_frac_active_replay
- FF_mean_active_rate_replay
- E_mean_active_rate_replay
- I_mean_active_rate_replay
- FF_ripple_envelope_ratio_replay
- E_ripple_envelope_ratio_replay
- I_ripple_envelope_ratio_replay
update_context:
- - optimize_simple_network
  - update_context
get_features_stages:
- source: optimize_simple_network
  compute_features: compute_features_run
- source: optimize_simple_network
  get_args_static: get_args_static_replay_event_ids
  compute_features: compute_features_replay
  filter_features: filter_features_replay
get_objectives:
  optimize_simple_network: get_objectives
kwargs:
  verbose: 1
  run_trial: 0
  replay_trial_offset: 0
  num_replay_trials: 5
  network_id: 908
  network_instance: 0
  connectivity_type: uniform
  default_weight_distribution_type: normal
  connection_weight_distribution_types:
    E:
      FF: lognormal
      E: lognormal
  input_types:
    FF: gaussian
  input_max_rates_run:
    FF: 20.
  input_min_rates_run:
    FF: 0.
  input_offline_min_rates:
    FF: 0.
  input_offline_max_rates:
    FF: 12.5  # 15.
  input_offline_fraction_active:
    FF: 0.25  # 0.3
  input_norm_tuning_widths:
    FF: 0.5
  structured_weight_params:
    E:  # target_pop_name
      source_pop_names:
        - FF
        - E
      tuning_type: additive
      norm_tuning_width: 0.5
  pop_cell_types:
    FF: input
    E: IB
    I: FS
  pop_sizes:
    FF: 1000
    E: 1000
    I: 200
  default_syn_mech_params:
    I:
      FF:
        g_unit: 0.0001925
      E:
        g_unit: 0.0001925
      I:
        g_unit: 0.0001925
    E:
      FF:
        g_unit: 0.0005275
      E:
        g_unit: 0.0005275
      I:
        g_unit: 0.0005275
objective_names:
- E_mean_peak_rate_run
- E_mean_min_rate_run
- I_mean_active_rate_run
- E_frac_active_run
- I_frac_active_run
- E_theta_envelope_ratio_run
- I_theta_envelope_ratio_run
- E_gamma_envelope_ratio_run
- I_gamma_envelope_ratio_run
# - E_centroid_theta_freq_run
# - I_centroid_theta_freq_run
# - E_centroid_gamma_freq_run
# - I_centroid_gamma_freq_run
- E_theta_tuning_index_run
- I_theta_tuning_index_run
- E_gamma_tuning_index_run
- I_gamma_tuning_index_run
# - E_frac_active_replay_residuals
- E_frac_active_replay
- E_mean_active_rate_replay
# - E_ripple_envelope_score
# - I_ripple_envelope_score
optimization_title: simple_network_J_reduced_rhyth
param_gen: PopulationAnnealing
param_names:
- E_FF_mean_weight
- E_E_mean_weight
- E_I_mean_weight
- I_FF_mean_weight
- I_E_mean_weight
- I_I_mean_weight
- E_FF_weight_norm_sigma
- E_E_weight_norm_sigma
- E_I_weight_norm_sigma
- I_FF_weight_norm_sigma
- I_E_weight_norm_sigma
- I_I_weight_norm_sigma
- E_E_tau_offset
- E_I_tau_offset
- I_E_tau_offset
- I_I_tau_offset
- E_E_syn_proportion
- E_E_FF_syn_proportion
- I_E_syn_proportion
- I_E_FF_syn_proportion
- E_norm_syn_count
- I_norm_syn_count
- E_peak_delta_weight
target_range:
  E_mean_peak_rate_run: 0.1
  E_mean_min_rate_run: 0.1
  I_mean_active_rate_run: 0.1
  E_frac_active_run: .001
  I_frac_active_run: .001
  E_theta_envelope_ratio_run: .01
  I_theta_envelope_ratio_run: .01
  E_gamma_envelope_ratio_run: .01
  I_gamma_envelope_ratio_run: .01
  E_centroid_theta_freq_run: 0.05
  I_centroid_theta_freq_run: 0.05
  E_centroid_gamma_freq_run: 0.5
  I_centroid_gamma_freq_run: 0.5
  E_theta_tuning_index_run: 0.2
  I_theta_tuning_index_run: 0.2
  E_gamma_tuning_index_run: 0.2
  I_gamma_tuning_index_run: 0.2
  E_frac_active_replay_residuals: 0.005
  E_frac_active_replay: 0.001
  E_mean_active_rate_replay: 0.1
  E_ripple_envelope_score: 0.01
  I_ripple_envelope_score: 0.01
target_val:
  E_mean_peak_rate_run: 20.
  E_mean_min_rate_run: 0.
  I_mean_active_rate_run: 20.
  E_frac_active_run: .6
  I_frac_active_run: .95
  E_theta_envelope_ratio_run: 0.
  I_theta_envelope_ratio_run: 0.
  E_gamma_envelope_ratio_run: 0.
  I_gamma_envelope_ratio_run: 0.
  E_centroid_theta_freq_run: 7.
  I_centroid_theta_freq_run: 7.
  E_centroid_gamma_freq_run: 70.
  I_centroid_gamma_freq_run: 70.
  E_theta_tuning_index_run: 0.
  I_theta_tuning_index_run: 0.
  E_gamma_tuning_index_run: 0.
  I_gamma_tuning_index_run: 0.
  E_frac_active_replay_residuals: 0.
x0:
  E_E_FF_syn_proportion: 5.558672E-01
  E_E_mean_weight: 7.666654E-01
  E_E_syn_proportion: 5.213730E-01
  E_E_tau_offset: 3.310981E+00
  E_E_weight_norm_sigma: 7.035587E-01
  E_FF_mean_weight: 1.318339E+00
  E_FF_weight_norm_sigma: 8.501778E-01
  E_I_mean_weight: 8.657889E-01
  E_I_tau_offset: 2.664080E+00
  E_I_weight_norm_sigma: 5.416425E-01
  E_norm_syn_count: 4.863112E-01
  E_peak_delta_weight: 3.754091E+00
  I_E_FF_syn_proportion: 4.980959E-01
  I_E_mean_weight: 1.665755E+00
  I_E_syn_proportion: 2.533030E-01
  I_E_tau_offset: 1.545679E+01
  I_E_weight_norm_sigma: 1.480687E-01
  I_FF_mean_weight: 1.725984E+00
  I_FF_weight_norm_sigma: 5.034243E-01
  I_I_mean_weight: 2.360475E-01
  I_I_tau_offset: 7.914728E+00
  I_I_weight_norm_sigma: 7.016509E-01
  I_norm_syn_count: 3.172796E-01
