verbose: 1
trial_offset: 0
network_id: 10
network_instance: 0
connectivity_type: uniform
default_weight_distribution_type: normal
connection_weight_distribution_types:
  E:
    FF: lognormal
    E: lognormal
input_types:
  FF: gaussian
input_offline_min_rates:
  FF: 0.
input_offline_max_rates:
  FF: 12.5  # 15.
input_offline_fraction_active:
  FF: 0.25
input_norm_tuning_widths:
  FF: 0.5
num_trials: 1000
structured_weight_params:
  E:  # target_pop_name
    source_pop_names:
      - FF
      - E
    tuning_type: additive
    norm_tuning_width: 0.5
    pop_over_representation:
      loc: 0.75
      width: 0.25
      depth: 0.25
pop_cell_types:
  FF: input
  E: IB
  I: FS
pop_sizes:
  FF: 1000
  E: 1000
  I: 200
default_syn_mech_params:
  I:
    FF:
      g_unit: 0.0001925
    E:
      g_unit: 0.0001925
    I:
      g_unit: 0.0001925
  E:
    FF:
      g_unit: 0.0005275
    E:
      g_unit: 0.0005275
    I:
      g_unit: 0.0005275
param_names:
  - E_FF_mean_weight
  - E_E_mean_weight
  - E_I_mean_weight
  - I_FF_mean_weight
  - I_E_mean_weight
  - I_I_mean_weight
  - E_FF_weight_norm_sigma
  - E_E_weight_norm_sigma
  - E_I_weight_norm_sigma
  - I_FF_weight_norm_sigma
  - I_E_weight_norm_sigma
  - I_I_weight_norm_sigma
  - E_E_tau_offset
  - E_I_tau_offset
  - I_E_tau_offset
  - I_I_tau_offset
  - E_E_syn_proportion
  - E_E_FF_syn_proportion
  - I_E_syn_proportion
  - I_E_FF_syn_proportion
  - E_norm_syn_count
  - I_norm_syn_count
  - E_peak_delta_weight
label: simple_network_J_reward_replay
x0:
  E_FF_mean_weight: 1.279704E-01
  E_E_mean_weight: 1.036678E+00
  E_I_mean_weight: 6.481184E-01
  I_FF_mean_weight: 4.252936E+00
  I_E_mean_weight: 8.319068E-01
  I_I_mean_weight: 3.831863E-01
  E_FF_weight_norm_sigma: 7.881238E-01
  E_E_weight_norm_sigma: 8.857694E-01
  E_I_weight_norm_sigma: 4.286916E-01
  I_FF_weight_norm_sigma: 7.701894E-01
  I_E_weight_norm_sigma: 6.443303E-01
  I_I_weight_norm_sigma: 2.394137E-01
  E_E_tau_offset: 4.940831E+00
  E_I_tau_offset: 4.252425E+00
  I_E_tau_offset: 1.696738E+01
  I_I_tau_offset: 7.602749E+00
  E_E_syn_proportion: 5.533530E-01
  E_E_FF_syn_proportion: 6.838711E-01
  I_E_syn_proportion: 4.776213E-01
  I_E_FF_syn_proportion: 1.110638E-01
  E_norm_syn_count: 4.415144E-01
  I_norm_syn_count: 1.615563E-01
  E_peak_delta_weight: 4.096247E+00
